repos:
  - repo: local
    hooks:
      - id: cleanup
        name: cleaning dependencies
        language: system
        entry: make cleanup

      - id: build
        name: building project
        language: system
        entry: make build
      
      - id: tests
        name: running tests
        language: system
        entry: make tests
